# Form implementation generated from reading ui file 'C:\Users\Admin\Documents\1. HỌC TẬP\5. KỸ THUẬT LẬP TRÌNH\FinalProject\LibraryManagementApp\View\Borrow_Return.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 553)
        MainWindow.setStyleSheet("/*Set style for Sidebar widget*/\n"
"#widgetSidebar {\n"
"    background-color: rgb(10, 102, 194);\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"}\n"
"\n"
"#widgetSidebar QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \"Montserrat Black\";\n"
"    font-size: 9px;\n"
"}\n"
"\n"
"#widgetSidebar QPushButton {\n"
"    background-color: rgb(10, 102, 194);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"Montserrat ExtraBold\";\n"
"    font-size: 9px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#widgetSidebar QPushButton:hover {\n"
"    background-color: rgb(11, 119, 226);\n"
"}\n"
"\n"
"#widgetSidebar QPushButton:pressed {\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"/*Set style for stacked widget main*/\n"
"#stackedWidgetMain {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"/*Set style for stacked widget Borrow funcs*/\n"
"#stackedWidgetBorrowFuncs {\n"
"    border: 3px solid rgb(10, 102, 194);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"/*Set style for page 0 of stacked widget Borrow funcs*/\n"
"#lbl_ID, #lbl_ISBN {\n"
"    color: rgb(10, 102, 194);\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#lblTitleBorrowBook {\n"
"    color: rgb(10, 102, 194);\n"
"    font-family: \"Montserrat Black\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#lineEdit_ID, #lineEdit_ISBN {\n"
"    background-color: #FFFBFB;\n"
"    border: 1px solid #e5ebf0;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font-family: \"Montserrat Medium\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#lineEdit_ID:focus, #lineEdit_ISBN:focus {\n"
"    border-color: rgb(10, 102, 194);\n"
"}\n"
"\n"
"#btnSearchBorrowBook {\n"
"    background-color: rgb(10, 102, 194);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#btnSearchBorrowBook:hover {\n"
"    background-color: rgb(8, 88, 168);\n"
"}\n"
"\n"
"#btnSearchBorrowBook:pressed {\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"/*Set style for page 1 of stacked widget Borrow funcs*/\n"
"#lbl_ID_2, #lbl_ISBN_2, #lbl_AvailableBooks, #lbl_NumberBorrowed, #lbl_AvailableQuantities {\n"
"    color: rgb(10, 102, 194);\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#lblTitleBorrowBook_2 {\n"
"    color: rgb(10, 102, 194);\n"
"    font-family: \"Montserrat Black\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#lineEdit_ID_2, #lineEdit_ISBN_2 {\n"
"    background-color: #FFFBFB;\n"
"    border: 1px solid #e5ebf0;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font-family: \"Montserrat Medium\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#lineEdit_ID_2:focus, #lineEdit_ISBN_2:focus {\n"
"    border-color: rgb(10, 102, 194);\n"
"}\n"
"\n"
"#spinBoxNumberBorrowed {\n"
"    background-color: #FFFBFB;\n"
"    border: 1px solid #e5ebf0;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font-family: \"Montserrat Medium\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#btnConfirmBorrowBook {\n"
"    background-color: rgb(10, 102, 194);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#btnConfirmBorrowBook:hover {\n"
"    background-color: rgb(8, 88, 168);\n"
"}\n"
"\n"
"#btnConfirmBorrowBook:pressed {\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"/*Set style for page 2 of stacked widget Borrow funcs*/\n"
"#lbl_ID_3, #lbl_ISBN_3, #lbl_AvailableBooks_2 {\n"
"    color: rgb(10, 102, 194);\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#lblTitleBorrowBook_3 {\n"
"    color: rgb(10, 102, 194);\n"
"    font-family: \"Montserrat Black\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#lbl_InvalidQuantity {\n"
"    color: rgb(255, 0, 0);\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#lineEdit_ID_3, #lineEdit_ISBN_3 {\n"
"    background-color: #FFFBFB;\n"
"    border: 1px solid #e5ebf0;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font-family: \"Montserrat Medium\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#lineEdit_ID_3:focus, #lineEdit_ISBN_3:focus {\n"
"    border-color: rgb(10, 102, 194);\n"
"}\n"
"\n"
"#btnRedoBorrow {\n"
"    background-color: rgb(10, 102, 194);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#btnRedoBorrow:hover {\n"
"    background-color: rgb(8, 88, 168);\n"
"}\n"
"\n"
"#btnRedoBorrow:pressed {\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"/*Set style for page 3 of stacked widget Borrow funcs*/\n"
"#lbl_ID_5, #lbl_ISBN_5, #lbl_AvailableBooks_4, #lbl_AvailableQuantities_2 {\n"
"    color: rgb(10, 102, 194);\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#lblTitleBorrowBook_5 {\n"
"    color: rgb(10, 102, 194);\n"
"    font-family: \"Montserrat Black\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#lineEdit_ID_5, #lineEdit_ISBN_5 {\n"
"    background-color: #FFFBFB;\n"
"    border: 1px solid #e5ebf0;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font-family: \"Montserrat Medium\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#lineEdit_ID_5:focus, #lineEdit_ISBN_5:focus {\n"
"    border-color: rgb(10, 102, 194);\n"
"}\n"
"\n"
"#lbl_CheckOut {\n"
"    color: rgb(77, 231, 0);\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#btnAddMore, #btnPrintReceipt {\n"
"    background-color: rgb(10, 102, 194);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#btnAddMore:hover, #btnPrintReceipt:hover {\n"
"    background-color: rgb(8, 88, 168);\n"
"}\n"
"\n"
"#btnAddMore:pressed, #btnPrintReceipt:pressed {\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"/*Set style for page 4 of Borrow funcs*/\n"
"#lbl_TitleReceipt {\n"
"    color: rgb(10, 102, 194);\n"
"    font-family: \"Montserrat Black\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#btnBackToBorrow {\n"
"    background-color: rgb(10, 102, 194);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#btnBackToBorrow:hover {\n"
"    background-color: rgb(8, 88, 168);\n"
"}\n"
"\n"
"#btnBackToBorrow:pressed {\n"
"    padding-left: 15px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(41, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widgetSidebar = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetSidebar.setMinimumSize(QtCore.QSize(151, 491))
        self.widgetSidebar.setMaximumSize(QtCore.QSize(151, 491))
        self.widgetSidebar.setObjectName("widgetSidebar")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widgetSidebar)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lbl_Logo = QtWidgets.QLabel(parent=self.widgetSidebar)
        self.lbl_Logo.setMinimumSize(QtCore.QSize(50, 50))
        self.lbl_Logo.setMaximumSize(QtCore.QSize(50, 50))
        self.lbl_Logo.setText("")
        self.lbl_Logo.setPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/Borrow_2.png"))
        self.lbl_Logo.setScaledContents(True)
        self.lbl_Logo.setObjectName("lbl_Logo")
        self.horizontalLayout_2.addWidget(self.lbl_Logo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lbl_Title = QtWidgets.QLabel(parent=self.widgetSidebar)
        self.lbl_Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_Title.setObjectName("lbl_Title")
        self.verticalLayout.addWidget(self.lbl_Title)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnBorrowBook = QtWidgets.QPushButton(parent=self.widgetSidebar)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/Borrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnBorrowBook.setIcon(icon)
        self.btnBorrowBook.setIconSize(QtCore.QSize(20, 20))
        self.btnBorrowBook.setObjectName("btnBorrowBook")
        self.verticalLayout_2.addWidget(self.btnBorrowBook)
        self.btnReturnBook = QtWidgets.QPushButton(parent=self.widgetSidebar)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/Return.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnReturnBook.setIcon(icon1)
        self.btnReturnBook.setIconSize(QtCore.QSize(20, 20))
        self.btnReturnBook.setObjectName("btnReturnBook")
        self.verticalLayout_2.addWidget(self.btnReturnBook)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.btnBackHome = QtWidgets.QPushButton(parent=self.widgetSidebar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/Homepage.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/Homepage.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.On)
        self.btnBackHome.setIcon(icon2)
        self.btnBackHome.setIconSize(QtCore.QSize(20, 20))
        self.btnBackHome.setObjectName("btnBackHome")
        self.verticalLayout_3.addWidget(self.btnBackHome)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.widgetSidebar)
        self.stackedWidgetMain = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidgetMain.setMinimumSize(QtCore.QSize(471, 491))
        self.stackedWidgetMain.setMaximumSize(QtCore.QSize(471, 491))
        self.stackedWidgetMain.setObjectName("stackedWidgetMain")
        self.pageDefault = QtWidgets.QWidget()
        self.pageDefault.setObjectName("pageDefault")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageDefault)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(parent=self.pageDefault)
        self.label.setMinimumSize(QtCore.QSize(241, 231))
        self.label.setMaximumSize(QtCore.QSize(350, 350))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Images/Borrow_BG.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.stackedWidgetMain.addWidget(self.pageDefault)
        self.pageBorrow = QtWidgets.QWidget()
        self.pageBorrow.setObjectName("pageBorrow")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pageBorrow)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.stackedWidgetBorrowFuncs = QtWidgets.QStackedWidget(parent=self.pageBorrow)
        self.stackedWidgetBorrowFuncs.setMinimumSize(QtCore.QSize(371, 411))
        self.stackedWidgetBorrowFuncs.setMaximumSize(QtCore.QSize(371, 411))
        self.stackedWidgetBorrowFuncs.setObjectName("stackedWidgetBorrowFuncs")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.gridLayout = QtWidgets.QGridLayout(self.page0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem9 = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem10, 1, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(30)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lblTitleBorrowBook = QtWidgets.QLabel(parent=self.page0)
        self.lblTitleBorrowBook.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitleBorrowBook.setObjectName("lblTitleBorrowBook")
        self.verticalLayout_13.addWidget(self.lblTitleBorrowBook)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(30)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lbl_ID = QtWidgets.QLabel(parent=self.page0)
        self.lbl_ID.setObjectName("lbl_ID")
        self.verticalLayout_10.addWidget(self.lbl_ID)
        self.lbl_ISBN = QtWidgets.QLabel(parent=self.page0)
        self.lbl_ISBN.setObjectName("lbl_ISBN")
        self.verticalLayout_10.addWidget(self.lbl_ISBN)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lineEdit_ID = QtWidgets.QLineEdit(parent=self.page0)
        self.lineEdit_ID.setMinimumSize(QtCore.QSize(100, 25))
        self.lineEdit_ID.setClearButtonEnabled(True)
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.verticalLayout_11.addWidget(self.lineEdit_ID)
        self.lineEdit_ISBN = QtWidgets.QLineEdit(parent=self.page0)
        self.lineEdit_ISBN.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_ISBN.setClearButtonEnabled(True)
        self.lineEdit_ISBN.setObjectName("lineEdit_ISBN")
        self.verticalLayout_11.addWidget(self.lineEdit_ISBN)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.btnSearchBorrowBook = QtWidgets.QPushButton(parent=self.page0)
        self.btnSearchBorrowBook.setMinimumSize(QtCore.QSize(80, 30))
        self.btnSearchBorrowBook.setMaximumSize(QtCore.QSize(80, 30))
        self.btnSearchBorrowBook.setObjectName("btnSearchBorrowBook")
        self.horizontalLayout_6.addWidget(self.btnSearchBorrowBook)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.gridLayout.addLayout(self.verticalLayout_13, 1, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem13, 1, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem14, 2, 1, 1, 1)
        self.stackedWidgetBorrowFuncs.addWidget(self.page0)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page1)
        self.gridLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem15 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 1, 0, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(30)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.lblTitleBorrowBook_2 = QtWidgets.QLabel(parent=self.page1)
        self.lblTitleBorrowBook_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitleBorrowBook_2.setObjectName("lblTitleBorrowBook_2")
        self.verticalLayout_20.addWidget(self.lblTitleBorrowBook_2)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(30)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(15)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lbl_ID_2 = QtWidgets.QLabel(parent=self.page1)
        self.lbl_ID_2.setObjectName("lbl_ID_2")
        self.verticalLayout_16.addWidget(self.lbl_ID_2)
        self.lbl_ISBN_2 = QtWidgets.QLabel(parent=self.page1)
        self.lbl_ISBN_2.setObjectName("lbl_ISBN_2")
        self.verticalLayout_16.addWidget(self.lbl_ISBN_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lineEdit_ID_2 = QtWidgets.QLineEdit(parent=self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.lineEdit_ID_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_ID_2.setSizePolicy(sizePolicy)
        self.lineEdit_ID_2.setMinimumSize(QtCore.QSize(30, 20))
        self.lineEdit_ID_2.setObjectName("lineEdit_ID_2")
        self.verticalLayout_17.addWidget(self.lineEdit_ID_2)
        self.lineEdit_ISBN_2 = QtWidgets.QLineEdit(parent=self.page1)
        self.lineEdit_ISBN_2.setObjectName("lineEdit_ISBN_2")
        self.verticalLayout_17.addWidget(self.lineEdit_ISBN_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_17)
        self.verticalLayout_18.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lbl_AvailableBooks = QtWidgets.QLabel(parent=self.page1)
        self.lbl_AvailableBooks.setObjectName("lbl_AvailableBooks")
        self.verticalLayout_14.addWidget(self.lbl_AvailableBooks)
        self.lbl_NumberBorrowed = QtWidgets.QLabel(parent=self.page1)
        self.lbl_NumberBorrowed.setObjectName("lbl_NumberBorrowed")
        self.verticalLayout_14.addWidget(self.lbl_NumberBorrowed)
        self.horizontalLayout_7.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lbl_AvailableQuantities = QtWidgets.QLabel(parent=self.page1)
        self.lbl_AvailableQuantities.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lbl_AvailableQuantities.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_AvailableQuantities.setObjectName("lbl_AvailableQuantities")
        self.verticalLayout_15.addWidget(self.lbl_AvailableQuantities)
        self.spinBoxNumberBorrowed = QtWidgets.QSpinBox(parent=self.page1)
        self.spinBoxNumberBorrowed.setObjectName("spinBoxNumberBorrowed")
        self.verticalLayout_15.addWidget(self.spinBoxNumberBorrowed)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_18.addLayout(self.horizontalLayout_7)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem17)
        self.btnConfirmBorrowBook = QtWidgets.QPushButton(parent=self.page1)
        self.btnConfirmBorrowBook.setMinimumSize(QtCore.QSize(100, 30))
        self.btnConfirmBorrowBook.setMaximumSize(QtCore.QSize(100, 30))
        self.btnConfirmBorrowBook.setObjectName("btnConfirmBorrowBook")
        self.horizontalLayout_8.addWidget(self.btnConfirmBorrowBook)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem18)
        self.verticalLayout_19.addLayout(self.horizontalLayout_8)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.gridLayout_2.addLayout(self.verticalLayout_20, 1, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 1, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 49, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem20, 2, 1, 1, 1)
        self.stackedWidgetBorrowFuncs.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem21 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem21, 0, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem22, 1, 0, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setSpacing(30)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.lblTitleBorrowBook_3 = QtWidgets.QLabel(parent=self.page2)
        self.lblTitleBorrowBook_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitleBorrowBook_3.setObjectName("lblTitleBorrowBook_3")
        self.verticalLayout_23.addWidget(self.lblTitleBorrowBook_3)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setSpacing(30)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(15)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.lbl_ID_3 = QtWidgets.QLabel(parent=self.page2)
        self.lbl_ID_3.setObjectName("lbl_ID_3")
        self.verticalLayout_24.addWidget(self.lbl_ID_3)
        self.lbl_ISBN_3 = QtWidgets.QLabel(parent=self.page2)
        self.lbl_ISBN_3.setObjectName("lbl_ISBN_3")
        self.verticalLayout_24.addWidget(self.lbl_ISBN_3)
        self.horizontalLayout_10.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.lineEdit_ID_3 = QtWidgets.QLineEdit(parent=self.page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ID_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_ID_3.setSizePolicy(sizePolicy)
        self.lineEdit_ID_3.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_ID_3.setObjectName("lineEdit_ID_3")
        self.verticalLayout_25.addWidget(self.lineEdit_ID_3)
        self.lineEdit_ISBN_3 = QtWidgets.QLineEdit(parent=self.page2)
        self.lineEdit_ISBN_3.setObjectName("lineEdit_ISBN_3")
        self.verticalLayout_25.addWidget(self.lineEdit_ISBN_3)
        self.horizontalLayout_10.addLayout(self.verticalLayout_25)
        self.verticalLayout_21.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lbl_AvailableBooks_2 = QtWidgets.QLabel(parent=self.page2)
        self.lbl_AvailableBooks_2.setObjectName("lbl_AvailableBooks_2")
        self.horizontalLayout_11.addWidget(self.lbl_AvailableBooks_2)
        self.lbl_InvalidQuantity = QtWidgets.QLabel(parent=self.page2)
        self.lbl_InvalidQuantity.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lbl_InvalidQuantity.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_InvalidQuantity.setObjectName("lbl_InvalidQuantity")
        self.horizontalLayout_11.addWidget(self.lbl_InvalidQuantity)
        self.verticalLayout_21.addLayout(self.horizontalLayout_11)
        self.verticalLayout_22.addLayout(self.verticalLayout_21)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem23)
        self.btnRedoBorrow = QtWidgets.QPushButton(parent=self.page2)
        self.btnRedoBorrow.setMinimumSize(QtCore.QSize(100, 30))
        self.btnRedoBorrow.setMaximumSize(QtCore.QSize(100, 30))
        self.btnRedoBorrow.setObjectName("btnRedoBorrow")
        self.horizontalLayout_12.addWidget(self.btnRedoBorrow)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem24)
        self.verticalLayout_22.addLayout(self.horizontalLayout_12)
        self.verticalLayout_23.addLayout(self.verticalLayout_22)
        self.gridLayout_3.addLayout(self.verticalLayout_23, 1, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem25, 1, 2, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem26, 2, 1, 1, 1)
        self.stackedWidgetBorrowFuncs.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem27, 1, 2, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setSpacing(30)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.lblTitleBorrowBook_5 = QtWidgets.QLabel(parent=self.page3)
        self.lblTitleBorrowBook_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitleBorrowBook_5.setObjectName("lblTitleBorrowBook_5")
        self.verticalLayout_36.addWidget(self.lblTitleBorrowBook_5)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setSpacing(30)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setSpacing(20)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setSpacing(15)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.lbl_ID_5 = QtWidgets.QLabel(parent=self.page3)
        self.lbl_ID_5.setObjectName("lbl_ID_5")
        self.verticalLayout_34.addWidget(self.lbl_ID_5)
        self.lbl_ISBN_5 = QtWidgets.QLabel(parent=self.page3)
        self.lbl_ISBN_5.setObjectName("lbl_ISBN_5")
        self.verticalLayout_34.addWidget(self.lbl_ISBN_5)
        self.horizontalLayout_16.addLayout(self.verticalLayout_34)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.lineEdit_ID_5 = QtWidgets.QLineEdit(parent=self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.lineEdit_ID_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_ID_5.setSizePolicy(sizePolicy)
        self.lineEdit_ID_5.setMinimumSize(QtCore.QSize(30, 20))
        self.lineEdit_ID_5.setObjectName("lineEdit_ID_5")
        self.verticalLayout_35.addWidget(self.lineEdit_ID_5)
        self.lineEdit_ISBN_5 = QtWidgets.QLineEdit(parent=self.page3)
        self.lineEdit_ISBN_5.setObjectName("lineEdit_ISBN_5")
        self.verticalLayout_35.addWidget(self.lineEdit_ISBN_5)
        self.horizontalLayout_16.addLayout(self.verticalLayout_35)
        self.verticalLayout_31.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lbl_AvailableBooks_4 = QtWidgets.QLabel(parent=self.page3)
        self.lbl_AvailableBooks_4.setObjectName("lbl_AvailableBooks_4")
        self.horizontalLayout_17.addWidget(self.lbl_AvailableBooks_4)
        self.lbl_AvailableQuantities_2 = QtWidgets.QLabel(parent=self.page3)
        self.lbl_AvailableQuantities_2.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lbl_AvailableQuantities_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_AvailableQuantities_2.setObjectName("lbl_AvailableQuantities_2")
        self.horizontalLayout_17.addWidget(self.lbl_AvailableQuantities_2)
        self.verticalLayout_31.addLayout(self.horizontalLayout_17)
        self.verticalLayout_32.addLayout(self.verticalLayout_31)
        self.lbl_CheckOut = QtWidgets.QLabel(parent=self.page3)
        self.lbl_CheckOut.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_CheckOut.setObjectName("lbl_CheckOut")
        self.verticalLayout_32.addWidget(self.lbl_CheckOut)
        self.verticalLayout_33.addLayout(self.verticalLayout_32)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(5)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem28)
        self.btnAddMore = QtWidgets.QPushButton(parent=self.page3)
        self.btnAddMore.setMinimumSize(QtCore.QSize(100, 30))
        self.btnAddMore.setMaximumSize(QtCore.QSize(100, 30))
        self.btnAddMore.setObjectName("btnAddMore")
        self.horizontalLayout_18.addWidget(self.btnAddMore)
        self.btnPrintReceipt = QtWidgets.QPushButton(parent=self.page3)
        self.btnPrintReceipt.setMinimumSize(QtCore.QSize(150, 30))
        self.btnPrintReceipt.setMaximumSize(QtCore.QSize(150, 30))
        self.btnPrintReceipt.setObjectName("btnPrintReceipt")
        self.horizontalLayout_18.addWidget(self.btnPrintReceipt)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem29)
        self.verticalLayout_33.addLayout(self.horizontalLayout_18)
        self.verticalLayout_36.addLayout(self.verticalLayout_33)
        self.horizontalLayout_19.addLayout(self.verticalLayout_36)
        self.gridLayout_4.addLayout(self.horizontalLayout_19, 1, 1, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem30, 0, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 49, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem31, 2, 1, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem32, 1, 0, 1, 1)
        self.stackedWidgetBorrowFuncs.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem33 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem33, 0, 1, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem34, 1, 0, 1, 1)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setSpacing(30)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.lbl_TitleReceipt = QtWidgets.QLabel(parent=self.page4)
        self.lbl_TitleReceipt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_TitleReceipt.setObjectName("lbl_TitleReceipt")
        self.verticalLayout_38.addWidget(self.lbl_TitleReceipt)
        self.tableView = QtWidgets.QTableView(parent=self.page4)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_38.addWidget(self.tableView)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem35)
        self.btnBackToBorrow = QtWidgets.QPushButton(parent=self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.btnBackToBorrow.sizePolicy().hasHeightForWidth())
        self.btnBackToBorrow.setSizePolicy(sizePolicy)
        self.btnBackToBorrow.setMinimumSize(QtCore.QSize(100, 30))
        self.btnBackToBorrow.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnBackToBorrow.setObjectName("btnBackToBorrow")
        self.horizontalLayout_20.addWidget(self.btnBackToBorrow)
        self.verticalLayout_37.addLayout(self.horizontalLayout_20)
        self.verticalLayout_38.addLayout(self.verticalLayout_37)
        self.gridLayout_5.addLayout(self.verticalLayout_38, 1, 1, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem36, 1, 2, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem37, 2, 1, 1, 1)
        self.stackedWidgetBorrowFuncs.addWidget(self.page4)
        self.horizontalLayout_4.addWidget(self.stackedWidgetBorrowFuncs)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem38)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        spacerItem39 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem39)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.stackedWidgetMain.addWidget(self.pageBorrow)
        self.horizontalLayout.addWidget(self.stackedWidgetMain)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem40)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidgetMain.setCurrentIndex(1)
        self.stackedWidgetBorrowFuncs.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_Title.setText(_translate("MainWindow", "BORROW/RETURN BOOKS"))
        self.btnBorrowBook.setText(_translate("MainWindow", " BORROW BOOK"))
        self.btnReturnBook.setText(_translate("MainWindow", " RETURN BOOK"))
        self.btnBackHome.setText(_translate("MainWindow", "BACK TO HOMEPAGE"))
        self.lblTitleBorrowBook.setText(_translate("MainWindow", "BORROW BOOK"))
        self.lbl_ID.setText(_translate("MainWindow", "ID"))
        self.lbl_ISBN.setText(_translate("MainWindow", "ISBN"))
        self.btnSearchBorrowBook.setText(_translate("MainWindow", "SEARCH"))
        self.lblTitleBorrowBook_2.setText(_translate("MainWindow", "BORROW BOOK"))
        self.lbl_ID_2.setText(_translate("MainWindow", "ID"))
        self.lbl_ISBN_2.setText(_translate("MainWindow", "ISBN"))
        self.lbl_AvailableBooks.setText(_translate("MainWindow", "Available Quantities"))
        self.lbl_NumberBorrowed.setText(_translate("MainWindow", "No. of books borrowed"))
        self.lbl_AvailableQuantities.setText(_translate("MainWindow", "2"))
        self.btnConfirmBorrowBook.setText(_translate("MainWindow", "CONFIRM"))
        self.lblTitleBorrowBook_3.setText(_translate("MainWindow", "BORROW BOOK"))
        self.lbl_ID_3.setText(_translate("MainWindow", "ID"))
        self.lbl_ISBN_3.setText(_translate("MainWindow", "ISBN"))
        self.lbl_AvailableBooks_2.setText(_translate("MainWindow", "Available Quantities"))
        self.lbl_InvalidQuantity.setText(_translate("MainWindow", "Invalid Quantity!"))
        self.btnRedoBorrow.setText(_translate("MainWindow", "REDO"))
        self.lblTitleBorrowBook_5.setText(_translate("MainWindow", "BORROW BOOK"))
        self.lbl_ID_5.setText(_translate("MainWindow", "ID"))
        self.lbl_ISBN_5.setText(_translate("MainWindow", "ISBN"))
        self.lbl_AvailableBooks_4.setText(_translate("MainWindow", "Available Quantities"))
        self.lbl_AvailableQuantities_2.setText(_translate("MainWindow", "2"))
        self.lbl_CheckOut.setText(_translate("MainWindow", "Check Out Successfully!"))
        self.btnAddMore.setText(_translate("MainWindow", "ADD MORE"))
        self.btnPrintReceipt.setText(_translate("MainWindow", "PRINT RECEIPT"))
        self.lbl_TitleReceipt.setText(_translate("MainWindow", "RECEIPT"))
        self.btnBackToBorrow.setText(_translate("MainWindow", "BACK"))
