
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\admin\PycharmProjects\pythonProject\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("898x605")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 605,
    width = 898,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    600.5,
    317.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#E7DCDC",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=464.0,
    y=293.0,
    width=273.0,
    height=46.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=444.0,
    y=467.0,
    width=313.0,
    height=48.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    600.5,
    404.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#E7DCDC",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=464.0,
    y=380.0,
    width=273.0,
    height=46.0
)

canvas.create_rectangle(
    0.0,
    0.0,
    299.0,
    605.0,
    fill="#0A66C2",
    outline="")

canvas.create_text(
    53.0,
    311.0,
    anchor="nw",
    text="LIBRARY MANAGEMENT",
    fill="#FFFFFF",
    font=("Montserrat Black", 15 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    150.0,
    219.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    606.0,
    135.0,
    image=image_image_2
)

canvas.create_text(
    533.0,
    209.0,
    anchor="nw",
    text="WELCOME BACK",
    fill="#0A66C2",
    font=("Montserrat Black", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
