# Form implementation generated from reading ui file 'C:\Users\Admin\Documents\1. HỌC TẬP\5. KỸ THUẬT LẬP TRÌNH\FinalProject\LibraryManagementApp\View\Homepage_User.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("/*Set style for Title widget*/\n"
"#widgetTitle {\n"
"    background-color: #0A66C2;\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"}\n"
"\n"
"#widgetTitle QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \"Righteous\";\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"/*Set style for Func widget*/\n"
"#widgetFuncs {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"#widgetFuncs QLabel {\n"
"    color: #0A66C2;\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#widgetFuncs QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 35px;\n"
"}\n"
"\n"
"#widgetFuncs QPushButton:hover {\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"\n"
"#widgetFuncs QPushButton:pressed {\n"
"    padding-left: 15px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widgetTitle = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetTitle.setMinimumSize(QtCore.QSize(300, 605))
        self.widgetTitle.setMaximumSize(QtCore.QSize(300, 605))
        self.widgetTitle.setObjectName("widgetTitle")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetTitle)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(parent=self.widgetTitle)
        self.label.setMinimumSize(QtCore.QSize(150, 150))
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/book.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widgetTitle)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widgetTitle)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widgetTitle)
        self.widgetFuncs = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetFuncs.setMinimumSize(QtCore.QSize(898, 605))
        self.widgetFuncs.setMaximumSize(QtCore.QSize(898, 605))
        self.widgetFuncs.setObjectName("widgetFuncs")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widgetFuncs)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(30)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.btnAccManage = QtWidgets.QPushButton(parent=self.widgetFuncs)
        self.btnAccManage.setMinimumSize(QtCore.QSize(150, 150))
        self.btnAccManage.setMaximumSize(QtCore.QSize(150, 150))
        self.btnAccManage.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/account_man_1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAccManage.setIcon(icon)
        self.btnAccManage.setIconSize(QtCore.QSize(80, 80))
        self.btnAccManage.setObjectName("btnAccManage")
        self.horizontalLayout_3.addWidget(self.btnAccManage)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.lblAcc = QtWidgets.QLabel(parent=self.widgetFuncs)
        self.lblAcc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAcc.setObjectName("lblAcc")
        self.verticalLayout_4.addWidget(self.lblAcc)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.btnBorrow = QtWidgets.QPushButton(parent=self.widgetFuncs)
        self.btnBorrow.setMinimumSize(QtCore.QSize(150, 150))
        self.btnBorrow.setMaximumSize(QtCore.QSize(150, 150))
        self.btnBorrow.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/borrow_1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnBorrow.setIcon(icon1)
        self.btnBorrow.setIconSize(QtCore.QSize(70, 75))
        self.btnBorrow.setObjectName("btnBorrow")
        self.horizontalLayout_4.addWidget(self.btnBorrow)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.lblBorrow = QtWidgets.QLabel(parent=self.widgetFuncs)
        self.lblBorrow.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblBorrow.setObjectName("lblBorrow")
        self.verticalLayout_5.addWidget(self.lblBorrow)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.btnStatistics = QtWidgets.QPushButton(parent=self.widgetFuncs)
        self.btnStatistics.setMinimumSize(QtCore.QSize(150, 150))
        self.btnStatistics.setMaximumSize(QtCore.QSize(150, 150))
        self.btnStatistics.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/statistics_1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStatistics.setIcon(icon2)
        self.btnStatistics.setIconSize(QtCore.QSize(80, 80))
        self.btnStatistics.setObjectName("btnStatistics")
        self.horizontalLayout_5.addWidget(self.btnStatistics)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.lblStatistics = QtWidgets.QLabel(parent=self.widgetFuncs)
        self.lblStatistics.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblStatistics.setObjectName("lblStatistics")
        self.verticalLayout_6.addWidget(self.lblStatistics)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem17)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2.addWidget(self.widgetFuncs)
        spacerItem18 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem18)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Library"))
        self.label_3.setText(_translate("MainWindow", "Management"))
        self.lblAcc.setText(_translate("MainWindow", "Account Management"))
        self.lblBorrow.setText(_translate("MainWindow", "Borrow/Return Books"))
        self.lblStatistics.setText(_translate("MainWindow", "Statistics"))
