# Form implementation generated from reading ui file 'C:\Users\Admin\Documents\1. HỌC TẬP\5. KỸ THUẬT LẬP TRÌNH\FinalProject\LibraryManagementApp\View\Log_In.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 599)
        MainWindow.setStyleSheet("/*Set style for Title widget*/\n"
"#widgetTitle {\n"
"    background-color: #0A66C2;\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"}\n"
"\n"
"#label_2, #label_3 {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family: \"Righteous\";\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"/*Set style for Log In widget*/\n"
"#widgetLogIn {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"#label_4 {\n"
"    color: rgb(0, 0, 0);\n"
"    font-family: \"Neue Einstellung SemiBold\";\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"#lblAccountInvalid {\n"
"    color: rgb(255, 0, 0);\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"/*Set style for QLineEdit*/\n"
"#widgetLogIn QLineEdit {\n"
"    background-color: #FFFBFB;\n"
"    border: 1px solid #e5ebf0;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font-family: \"Montserrat Medium\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#widgetLogIn QLineEdit:focus {\n"
"    border-color: #0A66C2;\n"
"}\n"
"\n"
"/*Set style for Log In button*/\n"
"#btnLogIn {\n"
"    background-color: #0A66C2;\n"
"    font-family: \"Montserrat SemiBold\";\n"
"    font-size: 20px;\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#btnLogIn:pressed {\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"#btnLogIn:hover, #btnLogIn:pressed {\n"
"    background-color: rgb(8, 88, 168);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.widgetTitle = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetTitle.setMinimumSize(QtCore.QSize(260, 391))
        self.widgetTitle.setMaximumSize(QtCore.QSize(260, 605))
        self.widgetTitle.setObjectName("widgetTitle")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widgetTitle)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 103, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lblBook = QtWidgets.QLabel(parent=self.widgetTitle)
        self.lblBook.setMinimumSize(QtCore.QSize(80, 80))
        self.lblBook.setMaximumSize(QtCore.QSize(150, 150))
        self.lblBook.setText("")
        self.lblBook.setPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/book.png"))
        self.lblBook.setScaledContents(True)
        self.lblBook.setObjectName("lblBook")
        self.horizontalLayout.addWidget(self.lblBook)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widgetTitle)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widgetTitle)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.widgetTitle, 0, 1, 1, 1)
        self.widgetLogIn = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetLogIn.setMinimumSize(QtCore.QSize(600, 391))
        self.widgetLogIn.setMaximumSize(QtCore.QSize(600, 605))
        self.widgetLogIn.setObjectName("widgetLogIn")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetLogIn)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(40)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(parent=self.widgetLogIn)
        self.label.setMinimumSize(QtCore.QSize(80, 80))
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("LibraryManagementApp/Ultilities/Icon/book_2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(parent=self.widgetLogIn)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(30)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.widgetLogIn)
        self.lineEditEmail.setMinimumSize(QtCore.QSize(400, 40))
        self.lineEditEmail.setClearButtonEnabled(True)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.verticalLayout_6.addWidget(self.lineEditEmail)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.widgetLogIn)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(400, 40))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setClearButtonEnabled(True)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_6.addWidget(self.lineEditPassword)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btnLogIn = QtWidgets.QPushButton(parent=self.widgetLogIn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLogIn.sizePolicy().hasHeightForWidth())
        self.btnLogIn.setSizePolicy(sizePolicy)
        self.btnLogIn.setMinimumSize(QtCore.QSize(0, 40))
        self.btnLogIn.setObjectName("btnLogIn")
        self.verticalLayout_7.addWidget(self.btnLogIn)
        self.lblAccountInvalid = QtWidgets.QLabel(parent=self.widgetLogIn)
        self.lblAccountInvalid.setText("")
        self.lblAccountInvalid.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAccountInvalid.setObjectName("lblAccountInvalid")
        self.verticalLayout_7.addWidget(self.lblAccountInvalid)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 59, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 59, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.widgetLogIn, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Library"))
        self.label_3.setText(_translate("MainWindow", "Management"))
        self.label_4.setText(_translate("MainWindow", "WELCOME BACK"))
        self.lineEditEmail.setPlaceholderText(_translate("MainWindow", "Email"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.btnLogIn.setText(_translate("MainWindow", "Log In"))
